### PR TITLE
Autoload the last used session

### PR DESCRIPTION
**Pull request by dansomething**
Autoload the last session that was open when the app exited. This also adds autosave for sessions named "Untitled" or "autosave*". 

@soulfresh I'm not sure if its desirable to autosave sessions that have already been autosaved or if it should just be for any "Untitled" session that was edited and not saved before exiting. Please give this branch a try and let me know what you think about the behavior when quitting the app with unsaved changes.

### CODE REVIEW

**Comment by soulfresh** [comment]
I just gave this a whirl and it works awesome! I really like the autosave feature and the unsaved warning on exit. The one thing I noticed is that it only saves the currently active preset. If I create multiple presets in the side menu, they should all be saved in the file.

**Comment by dansomething** [comment]
Sounds like a bug. Where are those presets coming from? Are they not part of the inputs-config?

**Comment by soulfresh** [comment]
I just realized this might take a little refactoring to get working. The presets are currently managed by the presets directive. Since it's a directive, you probably won't have easy access to it's scope. We should move all the logic for managing presets into a service that you can access when you're saving the session. Then the preset directive can be as simple as calling the correct methods on the service.

**Comment by dansomething** [comment]
@soulfresh if you think the behavior is ok then I'd like to get this merged and work on the preset issue in new ticket. It seems like a separate problem that can be worked independently. What do you think?

**Comment by soulfresh** [comment]
Do it!

**Pull request merged**
